version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: harmalh-hermes-workspace_workspace_1
      APP_PORT: 3000

  workspace:
    image: ghcr.io/harmalh/hermes-workspace-ui-umbrel:0.1.0@sha256:f473fb62f407fb59b547721d08b98afd0471ccd4077b5a2d0b9c6db4faf0ce46
    restart: on-failure
    init: true
    depends_on: [hermes-api]
    environment:
      NODE_ENV: "production"
      HERMES_API_URL: "http://hermes-api:8642"

  hermes-api:
    image: ghcr.io/harmalh/hermes-workspace-api-umbrel:0.1.0@sha256:5aad6abb76d6d21b1d498e00d2ad780ea853d3bd8de01663b186ece60f2eded4
    restart: on-failure
    init: true
    stop_grace_period: 1m
    environment:
      HOME: /opt/hermes-home
    volumes:
      - ${APP_DATA_DIR}/hermes:/opt/hermes-home
