version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: harmalh-hermes-workspace_workspace_1
      APP_PORT: 3000

  workspace:
    image: ghcr.io/harmalh/hermes-workspace-ui-umbrel:0.1.4@sha256:3cb92a27b8cb932ebaa9a65d42b561e3969f3913e26f4d7a89f5a7d58a6e4925
    restart: on-failure
    init: true
    depends_on: [hermes-api]
    environment:
      NODE_ENV: "production"
      HERMES_API_URL: "http://hermes-api:8642"

  hermes-api:
    image: ghcr.io/harmalh/hermes-workspace-api-umbrel:0.1.4@sha256:afdf50c7c9b5b9f9f8372841d4aa652c7434ecab0026270df8ba9725767667b2
    restart: on-failure
    init: true
    stop_grace_period: 1m
    environment:
      API_SERVER_ENABLED: "true"
      API_SERVER_HOST: "0.0.0.0"
      API_SERVER_PORT: "8642"
      HOME: /opt/hermes-home
    volumes:
      - ${APP_DATA_DIR}/hermes:/opt/hermes-home
